-- Table: positions
CREATE TABLE positions (
    position_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);


-- Table: sub_positions
CREATE TABLE sub_positions (
    name VARCHAR PRIMARY KEY,
    position_id INTEGER NOT NULL
);

-- Foreign Key: sub_positions.position_id → positions.position_id
ALTER TABLE sub_positions
    ADD CONSTRAINT subpositions_position_id_fkey
    FOREIGN KEY (position_id) REFERENCES positions(position_id);


-- Table: countries
CREATE TABLE countries (
    name TEXT PRIMARY KEY
);


-- Table: competitions
CREATE TABLE competitions (
    competition_id TEXT PRIMARY KEY,
    name VARCHAR NOT NULL,
    url TEXT,
    is_major_national_league BOOLEAN DEFAULT FALSE,
    country_name VARCHAR NOT NULL
);

-- Foreign Key: competitions.country_name → countries.name
ALTER TABLE competitions
    ADD CONSTRAINT competitions_country_name_fkey
    FOREIGN KEY (country_name) REFERENCES countries(name);


-- Table: clubs
CREATE TABLE clubs (
    club_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    domestic_competition_id TEXT,
    stadium_name VARCHAR,
    stadium_seats INTEGER,
    squad_size INTEGER,
    average_age NUMERIC,
    foreigners_number INTEGER,
    national_team_players INTEGER
);


-- Table: players
CREATE TABLE players (
    player_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    date_of_birth DATE,
    sub_position TEXT,
    height_in_cm REAL,
    foot VARCHAR,
    current_club_id INTEGER,
    country_of_citizenship TEXT
);

-- FKs for players
ALTER TABLE players
    ADD CONSTRAINT players_current_club_id_fkey
    FOREIGN KEY (current_club_id) REFERENCES clubs(club_id);

ALTER TABLE players
    ADD CONSTRAINT players_sub_position_fkey
    FOREIGN KEY (sub_position) REFERENCES sub_positions(name);

ALTER TABLE players
    ADD CONSTRAINT players_country_of_citizenship_fkey
    FOREIGN KEY (country_of_citizenship) REFERENCES countries(name);


-- Table: games
CREATE TABLE games (
    game_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    home_club_id INTEGER,
    away_club_id INTEGER,
    competition_id TEXT,
    home_club_goals INTEGER,
    away_club_goals INTEGER,
    date DATE,
    home_club_position INTEGER,
    away_club_position INTEGER,
    season VARCHAR
);

-- FKs for games
ALTER TABLE games
    ADD CONSTRAINT games_home_club_id_fkey
    FOREIGN KEY (home_club_id) REFERENCES clubs(club_id);

ALTER TABLE games
    ADD CONSTRAINT games_away_club_id_fkey
    FOREIGN KEY (away_club_id) REFERENCES clubs(club_id);

ALTER TABLE games
    ADD CONSTRAINT games_competition_id_fkey
    FOREIGN KEY (competition_id) REFERENCES competitions(competition_id);


-- Table: transfers
CREATE TABLE transfers (
    transfer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id INTEGER,
    from_club_id INTEGER,
    to_club_id INTEGER,
    transfer_date DATE,
    transfer_season VARCHAR,
    transfer_fee INTEGER,
    market_value_in_eur INTEGER
);

-- FKs for transfers
ALTER TABLE transfers
    ADD CONSTRAINT transfers_player_id_fkey
    FOREIGN KEY (player_id) REFERENCES players(player_id);

ALTER TABLE transfers
    ADD CONSTRAINT transfers_from_club_id_fkey
    FOREIGN KEY (from_club_id) REFERENCES clubs(club_id);

ALTER TABLE transfers
    ADD CONSTRAINT transfers_to_club_id_fkey
    FOREIGN KEY (to_club_id) REFERENCES clubs(club_id);


-- Indexes
CREATE INDEX IF NOT EXISTS idx_players_current_club_id
    ON players(current_club_id);

CREATE INDEX IF NOT EXISTS idx_games_home_club_id
    ON games(home_club_id);

CREATE INDEX IF NOT EXISTS idx_games_away_club_id
    ON games(away_club_id);

CREATE INDEX IF NOT EXISTS idx_games_competition_id
    ON games(competition_id);

CREATE INDEX IF NOT EXISTS idx_transfers_player_id
    ON transfers(player_id);

CREATE INDEX IF NOT EXISTS idx_transfers_from_club_id
    ON transfers(from_club_id);

CREATE INDEX IF NOT EXISTS idx_transfers_to_club_id
    ON transfers(to_club_id);

CREATE INDEX IF NOT EXISTS idx_sub_positions_position_id
    ON sub_positions(position_id);

CREATE INDEX IF NOT EXISTS idx_competitions_country_name
    ON competitions(country_name);

CREATE INDEX IF NOT EXISTS idx_players_country_of_citizenship
    ON players(country_of_citizenship);
